package com.agapehill.agape_hill_backend.service.impl;

import com.agapehill.agape_hill_backend.domain.entity.SchoolEventEntity;
import com.agapehill.agape_hill_backend.domain.entity.StudentEventPaymentEntity;
import com.agapehill.agape_hill_backend.dto.request.EventRequest;
import com.agapehill.agape_hill_backend.dto.response.*;
import com.agapehill.agape_hill_backend.repository.*;
import com.agapehill.agape_hill_backend.service.EventService;
import lombok.RequiredArgsConstructor;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import reactor.core.publisher.Mono;

import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.List;
import java.util.UUID;

@Service
@RequiredArgsConstructor
public class EventServiceImpl implements EventService {

    private final SchoolEventRepository eventRepo;
    private final StudentEventPaymentRepository paymentRepo;
    private final StudentRepository studentRepo;

    @Override
    @Transactional
    public Mono<WsResponse<EventSummaryResponse>> createEvent(EventRequest request) {
        
        BigDecimal fee = request.getRegistrationFee() != null ? request.getRegistrationFee() : BigDecimal.ZERO;

        // Passing 'null' as the first parameter triggers an INSERT operation
        SchoolEventEntity event = new SchoolEventEntity(
                null, 
                request.getTitle(),
                request.getEventDate(),
                request.getEventTime(),
                fee,
                LocalDateTime.now()
        );

        return eventRepo.save(event)
                .map(saved -> new WsResponse<>(
                        new WsHeader("200", "School Event Created Cleanly"),
                        new EventSummaryResponse(
                            saved.getId(), // Contains the UUID generated by PostgreSQL
                            saved.getTitle(), 
                            saved.getEventDate(), 
                            saved.getEventTime(), 
                            saved.getRegistrationFee(), 
                            0L, 
                            BigDecimal.ZERO
                        )
                ));
    }

    @Override
    public Mono<WsResponse<List<EventSummaryResponse>>> getAllEvents() {
        return eventRepo.findAll()
                .flatMap(event -> 
                    Mono.zip(
                        paymentRepo.countParticipantsByEventId(event.getId()).defaultIfEmpty(0L),
                        paymentRepo.sumAmountPaidByEventId(event.getId()).defaultIfEmpty(BigDecimal.ZERO)
                    ).map(tuple -> new EventSummaryResponse(
                            event.getId(),
                            event.getTitle(),
                            event.getEventDate(),
                            event.getEventTime(),
                            event.getRegistrationFee(),
                            tuple.getT1(),
                            tuple.getT2()
                    ))
                )
                .collectList()
                .map(list -> new WsResponse<>(new WsHeader("200", "Events list fetched dynamically"), list));
    }

    @Override
    public Mono<WsResponse<List<EventLedgerItemResponse>>> getEventLedger(UUID eventId) {
        return paymentRepo.findByEventId(eventId)
                .flatMap(payment -> 
                    studentRepo.findById(payment.getStudentId())
                        // 👈 Defensive Fallback: Keeps the row alive even if the student entity isn't fully found yet
                        .map(student -> new EventLedgerItemResponse(
                                student.getId(),
                                student.getFullName(),
                                student.getAdmissionNumber(),
                                payment.getAmountPaid()
                        ))
                        .defaultIfEmpty(new EventLedgerItemResponse(
                                payment.getStudentId(),
                                "Unknown Student (Unlinked Profile)",
                                "N/A",
                                payment.getAmountPaid()
                        ))
                )
                .collectList()
                .map(list -> new WsResponse<>(
                        new WsHeader("200", "Ledger stream synchronized"), 
                        list
                ));
    }

    @Override
    @Transactional
    public Mono<WsResponse<Void>> logEventPayment(UUID eventId, EventRequest request) {
        BigDecimal amountToAdd = request.getAmountPaid() != null ? request.getAmountPaid() : BigDecimal.ZERO;

        return paymentRepo.findByEventIdAndStudentId(eventId, request.getStudentId())
                .flatMap(existingRecord -> {
                    existingRecord.setAmountPaid(existingRecord.getAmountPaid().add(amountToAdd));
                    return paymentRepo.save(existingRecord);
                })
                .switchIfEmpty(
                    Mono.defer(() -> {
                        // Passing 'null' as the first parameter forces an INSERT operation
                        StudentEventPaymentEntity newRecord = new StudentEventPaymentEntity(
                                null, 
                                eventId,
                                request.getStudentId(),
                                amountToAdd,
                                LocalDateTime.now()
                        );
                        return paymentRepo.save(newRecord);
                    })
                )
                .then(Mono.just(new WsResponse<>(new WsHeader("200", "Transaction completed successfully"), null)));
    }
}