spring.application.name=agape_hill_backend

########################################
# R2DBC (Runtime – Reactive access)
########################################
spring.r2dbc.url=r2dbc:postgresql://localhost:5432/agape_hill_db?schema=school
spring.r2dbc.username=postgres
spring.r2dbc.password=root

# Logs the SQL statements
logging.level.org.springframework.r2dbc=DEBUG

# Logs the actual values being bound to the $1, $2, etc.
logging.level.io.r2dbc.postgresql.QUERY=DEBUG
logging.level.io.r2dbc.postgresql.PARAM=DEBUG

